"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xjj7HMB0jzEsIlqDPR5djfdinASWqIE4
"""

import os
import pandas as pd
import re
import streamlit as st
from langchain_groq import ChatGroq
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.documents import Document
from rank_bm25 import BM25Okapi
from sentence_transformers import CrossEncoder

os.environ["GROQ_API_KEY"] = st.secrets["GROQ_API_KEY"]

st.set_page_config(page_title="Hospital AI", page_icon="🏥", layout="wide")
st.markdown("""
    <style>
    .main { background-color: #f5f7f9; }
    .stButton>button { width: 100%; border-radius: 5px; height: 3em; background-color: #007bff; color: white; }
    </style>
    """, unsafe_allow_html=True)

data_dir = "hospital_data"

hospitals = pd.read_csv(f"{data_dir}/hospitals.csv", index_col=False)
physicians = pd.read_csv(f"{data_dir}/physicians.csv", index_col=False)
payers = pd.read_csv(f"{data_dir}/payers.csv", index_col=False)
reviews = pd.read_csv(f"{data_dir}/reviews.csv", index_col=False)
patients = pd.read_csv(f"{data_dir}/patients.csv", index_col=False)
visits = pd.read_csv(f"{data_dir}/visits.csv", index_col=False)

def normalize_text(text):
    if pd.isna(text): return text
    patterns = [r'\bMr\.\b', r'\bMiss\b', r'\bMrs\.\b', r'\bMs\.\b', r'\bDr\.\b', r'\bDDS\b', r'\bMD\b', r'\bJr\.\b', r'\bSr\.\b']
    for p in patterns:
        text = re.sub(p, '', text)
    return text.replace('"', '').strip()

for df, col in [(hospitals, "hospital_name"), (physicians, "physician_name"), (patients, "patient_name")]:
    df[col] = df[col].apply(normalize_text)

for df in [visits, patients, hospitals, physicians, payers]:
    for col in ['patient_id', 'hospital_id', 'physician_id', 'payer_id']:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')

master_df = visits.merge(patients, on="patient_id", how="left") \
                  .merge(hospitals, on="hospital_id", how="left") \
                  .merge(physicians, on="physician_id", how="left") \
                  .merge(payers, on="payer_id", how="left") \
                  .merge(reviews[['visit_id', 'review']], on="visit_id", how="left")

def create_rag_string(row):
    name = row['patient_name'] if pd.notna(row['patient_name']) else f"Unknown Patient (ID: {row['patient_id']})"
    spec = f" ({row['medical_specialty']})" if 'medical_specialty' in row and pd.notna(row['medical_specialty']) else ""
    complaint = f" Chief Complaint: {row['chief_complaint']}." if pd.notna(row['chief_complaint']) else ""
    return (f"Patient {name} (Blood Type: {row.get('patient_blood_type', 'N/A')}) "
            f"visited {row.get('hospital_name', 'Unknown Hospital')} in {row.get('hospital_state', 'N/A')}. "
            f"Doctor: {row.get('physician_name', 'Unknown')}{spec}. Insurance: {row.get('payer_name', 'N/A')}. "
            f"Admission: {row.get('admission_type', 'N/A')}. {complaint} Results: {row.get('test_results', 'N/A')}. "
            f"Billing: ${row.get('billing_amount', 0):,.2f}. Feedback: {row.get('review', 'None.')}")

master_df['info_for_bot'] = master_df.apply(create_rag_string, axis=1)
master_df.to_csv("master_merged.csv", index=False)

@st.cache_resource
def load_hospital_engine():
    embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
    
    docs = []
    for _, row in master_df.iterrows():
        docs.append(Document(
            page_content=row['info_for_bot'],
            metadata={
                "state": row['hospital_state'],
                "patient_id": int(row['patient_id']),
                "hospital": row['hospital_name']
            }
        ))
    
    vector_db = FAISS.from_documents(docs, embeddings)
    tokenized_corpus = [doc.page_content.split(" ") for doc in docs]
    bm25_index = BM25Okapi(tokenized_corpus)
    
    llm = ChatGroq(model_name="llama-3.1-8b-instant", temperature=0)
    reranker = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')
    
    return vector_db, llm, reranker, bm25_index

vector_db, llm, reranker, bm25_index = load_hospital_engine()

template = """You are a professional hospital assistant. Answer based ONLY on context and history.
Context: {context}
Chat History: {chat_history}
Question: {question}
Answer:"""
prompt = ChatPromptTemplate.from_template(template)

REWRITE_PROMPT = ChatPromptTemplate.from_template("""
You are a query re-writer for a Hospital RAG system. 
Your goal is to look at the Chat History and the New Question, and create a single, clear search query that includes the specific Patient or Physician name being discussed.

Rules:
1. If the user uses pronouns like "his", "her", or "their", replace them with the name of the person discussed earlier in the history.
2. Ignore purely numerical answers in the history when looking for the subject.
3. If no person is mentioned in history, return the question as is.

Chat History:
{chat_history}

New Question: {question}
Standalone Search Query:""")

def ask_hospital_bot(query, chat_history_list):
    history_str = "\n".join([f"{msg['role']}: {msg['content']}" for msg in chat_history_list[-3:]])

    rewriter_chain = REWRITE_PROMPT | llm | StrOutputParser()
    try:
        standalone_query = rewriter_chain.invoke({
            "chat_history": history_str, 
            "question": query
        })
    except Exception:
        # Fallback to original query if the API call fails
        standalone_query = query

    vector_results = vector_db.similarity_search(standalone_query, k=10)
    vector_texts = [res.page_content for res in vector_results]

    tokenized_query = standalone_query.split(" ")
    bm25_texts = bm25_index.get_top_n(tokenized_query, master_df['info_for_bot'].tolist(), n=10)

    all_candidates = list(set(vector_texts + bm25_texts))
    pairs = [[standalone_query, cand] for cand in all_candidates]
    scores = reranker.predict(pairs)
    final_context = [cand for _, cand in sorted(zip(scores, all_candidates), reverse=True)][:3]

    gen_chain = prompt | llm | StrOutputParser()
    response = gen_chain.invoke({
        "context": "\n\n".join(final_context),
        "chat_history": history_str,
        "question": query
    })

    return response

with st.sidebar:
    st.header("🛠️ System Control")
    st.success("✅ FAISS Index: Connected")
    st.info("🤖 Model: Llama-3.1-8b")
    st.warning("🔍 Retrieval: Hybrid (BM25 + Vector)")

    st.divider()
    if st.button("🗑️ Clear Chat History"):
        st.session_state.messages = []
        st.rerun()

tab1, tab2 = st.tabs(["💬 AI Assistant", "📊 Database Preview"])

with tab2:
    st.subheader("Master Data Inspection")
    try:
        df = pd.read_csv("master_merged.csv")
        st.dataframe(df, use_container_width=True)
    except:
        st.error("Master CSV not found.")

with tab1:
    st.title("🏥 Hospital Intelligence System")
    st.write("Ask me about patients, physicians, insurance, or hospital reviews.")

    st.markdown("### 💡 Quick Queries")
    p_col1, p_col2, p_col3 = st.columns(3)
    p_col4, p_col5, p_col6 = st.columns(3)

    example_prompts = [
        "Who was the physician for Michael Bradshaw?",
        "List top 3 reviews for hospitals in Florida.",
        "What insurance does Andrew Miller use?",
        "Find a patient with billing over $30,000.",
        "List 5 patients covered by Medicaid & visited a hospital in NC.",
        "From reviews, which hospital is best for emergency care?"
    ]

    selected_prompt = None

    with p_col1:
        if st.button(example_prompts[0]): selected_prompt = example_prompts[0]
    with p_col2:
        if st.button(example_prompts[1]): selected_prompt = example_prompts[1]
    with p_col3:
        if st.button(example_prompts[2]): selected_prompt = example_prompts[2]
    with p_col4:
        if st.button(example_prompts[3]): selected_prompt = example_prompts[3]
    with p_col5:
        if st.button(example_prompts[4]): selected_prompt = example_prompts[4]
    with p_col6:
        if st.button(example_prompts[5]): selected_prompt = example_prompts[5]

    if "messages" not in st.session_state:
        st.session_state.messages = []

    for msg in st.session_state.messages:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

    user_input = st.chat_input("Enter your query here...")
    final_query = selected_prompt if selected_prompt else user_input

    if final_query:
        st.session_state.messages.append({"role": "user", "content": final_query})
        with st.chat_message("user"):
            st.markdown(final_query)

        with st.chat_message("assistant"):
            with st.spinner("Analyzing hospital records..."):
                response = ask_hospital_bot(final_query, st.session_state.messages)
                st.markdown(response)
                st.session_state.messages.append({"role": "assistant", "content": response})
